# Generated by Django 4.2.6 on 2023-11-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodball_player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20)),
                ('p_age', models.IntegerField()),
                ('p_country', models.CharField(max_length=20)),
                ('p_email', models.EmailField(max_length=254)),
                ('p_dob', models.DateField()),
            ],
        ),
    ]
